# Generated by Django 4.1.6 on 2023-02-11 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('rank', models.CharField(max_length=50)),
                ('area_of_assignment', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('employee_status', models.CharField(max_length=15)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('hightest_educational_level', models.CharField(max_length=50, verbose_name='highest educational level')),
                ('degree', models.CharField(max_length=50, verbose_name='degree')),
                ('ra_1080', models.BooleanField(default=False)),
                ('ra_9258', models.BooleanField(default=False)),
                ('csc_prof', models.BooleanField(default=False)),
                ('csc_sub_prof', models.BooleanField(default=False)),
                ('pd_907', models.BooleanField(default=False)),
                ('tesda', models.BooleanField(default=False)),
                ('length_of_service', models.IntegerField(blank=True, null=True)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='address',
            name='personnel',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personnel'),
            preserve_default=False,
        ),
    ]
