# Generated by Django 3.1.7 on 2023-03-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile_images/'),
        ),
    ]
