# Generated by Django 3.1.7 on 2023-03-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_personnel_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='rank',
        ),
    ]
