# Generated by Django 4.1.6 on 2023-02-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_personnel_remove_address_customer_delete_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='personnel',
        ),
    ]
