# Generated by Django 3.1.7 on 2023-02-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230202_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='length_of_service',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
