# Generated by Django 4.1.6 on 2023-02-11 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_address_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='personnel',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personnel'),
            preserve_default=False,
        ),
    ]
