# Generated by Django 3.1.7 on 2023-03-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0008_auto_20230318_1954'),
        ('account', '0004_personnel_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.rank', verbose_name='Rank'),
        ),
    ]
