# Generated by Django 3.1.7 on 2023-02-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230202_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
