# Generated by Django 3.1.7 on 2023-04-01 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0018_auto_20230401_0922'),
        ('account', '0005_auto_20230321_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='area_of_assignment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='degree'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='employee_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='hightest_educational_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='highest educational level'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pasundayag.rank', verbose_name='Rank'),
        ),
    ]
