# Generated by Django 3.1.7 on 2023-03-31 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0022_auto_20230331_2225'),
        ('account', '0007_auto_20230331_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasundayag.rank', verbose_name='Rank'),
        ),
    ]
