# Generated by Django 3.1.7 on 2023-03-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20230331_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='area_of_assignment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='degree'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='employee_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='hightest_educational_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='highest educational level'),
        ),
    ]
