# Generated by Django 3.1.7 on 2023-02-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'IPCR', 'verbose_name_plural': 'IPCRs'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Employement Status', 'verbose_name_plural': 'Employement Status'},
        ),
    ]
