# Generated by Django 3.1.7 on 2023-02-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='rank',
        ),
        migrations.AddField(
            model_name='area',
            name='rank',
            field=models.ManyToManyField(to='pasundayag.Rank'),
        ),
    ]
