# Generated by Django 3.1.7 on 2023-02-06 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Rank', 'verbose_name_plural': 'Ranks'},
        ),
    ]
