# Generated by Django 3.1.7 on 2023-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr',
            name='core_total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
