# Generated by Django 3.1.7 on 2023-02-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='ipcr',
            name='regular_price',
        ),
        migrations.RemoveField(
            model_name='ipcr',
            name='users_wishlist',
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='ipcr_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.ipcrtype', verbose_name='IPCR Type'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Change IPCR visibility', verbose_name='IPCR visibility'),
        ),
        migrations.AlterField(
            model_name='ipcrspecification',
            name='ipcr_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.ipcrtype', verbose_name='IPCR Type'),
        ),
    ]
