# Generated by Django 3.1.7 on 2023-02-12 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasundayag', '0002_auto_20230211_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.rank')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfo_paf', models.TextField(blank=True, null=True)),
                ('indicators', models.TextField(blank=True, null=True)),
                ('accomplishments', models.TextField(blank=True, null=True)),
                ('q', models.FloatField()),
                ('e', models.FloatField()),
                ('t', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasundayag.function')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfo_paf', models.TextField(blank=True, null=True)),
                ('indicators', models.TextField(blank=True, null=True)),
                ('accomplishments', models.TextField(blank=True, null=True)),
                ('q', models.FloatField()),
                ('e', models.FloatField()),
                ('t', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasundayag.item')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel_IPCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.rank')),
            ],
        ),
    ]
