# Generated by Django 3.1.7 on 2023-02-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0002_auto_20230216_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='year',
        ),
        migrations.RemoveField(
            model_name='subfunction',
            name='year',
        ),
    ]
