# Generated by Django 3.1.7 on 2023-02-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0002_ipcr_core_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr',
            name='core_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
