# Generated by Django 3.1.7 on 2023-02-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0003_function_item_personnel_ipcr_subitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='description',
            field=models.CharField(default='Description', max_length=255),
        ),
    ]
