# Generated by Django 3.1.7 on 2023-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0003_auto_20230207_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr',
            name='adjectival_core_total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ipcr',
            name='adjectival_stra_total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ipcr',
            name='adjectival_supp_total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
