# Generated by Django 3.1.7 on 2023-03-18 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasundayag', '0004_auto_20230318_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr',
            name='personnel',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(_negated=True, is_superuser=True), models.Q(_negated=True, is_staff=True)), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
