# Generated by Django 3.1.7 on 2023-02-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0004_function_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
