# Generated by Django 3.1.7 on 2023-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0004_auto_20230207_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr',
            name='adjectival_stra_total',
        ),
        migrations.AddField(
            model_name='ipcr',
            name='stra_adjectival_rating',
            field=models.CharField(default='Poor', max_length=255, verbose_name='Final Adjectival Rating'),
        ),
    ]
