# Generated by Django 3.1.7 on 2023-02-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0005_auto_20230212_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'Function', 'verbose_name_plural': 'Functions'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='subitem',
            options={'verbose_name': 'Subitem', 'verbose_name_plural': 'Subitems'},
        ),
        migrations.AlterField(
            model_name='item',
            name='e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='q',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='t',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='q',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='t',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
