# Generated by Django 3.1.7 on 2023-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0005_auto_20230207_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr',
            name='adjectival_core_total',
        ),
        migrations.AddField(
            model_name='ipcr',
            name='core_adjectival_rating',
            field=models.CharField(default='Poor', max_length=255, verbose_name='Final Adjectival Rating'),
        ),
    ]
