# Generated by Django 3.1.7 on 2023-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0006_auto_20230207_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr',
            name='adjectival_supp_total',
        ),
        migrations.AddField(
            model_name='ipcr',
            name='supp_adjectival_rating',
            field=models.CharField(default='Poor', max_length=255, verbose_name='Support Function Adjectival Rating'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='core_adjectival_rating',
            field=models.CharField(default='Poor', max_length=255, verbose_name='Core Function Adjectival Rating'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_adjectival_rating',
            field=models.CharField(default='Poor', max_length=255, verbose_name='Strategic Function Adjectival Rating'),
        ),
    ]
