# Generated by Django 3.1.7 on 2023-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0006_auto_20230318_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr',
            name='core_acad_adjectival_rating',
            field=models.CharField(blank=True, default='Poor', max_length=255, verbose_name='Core Functions - Academic Adjectival Rating'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='core_acad_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='core_prod_adjectival_rating',
            field=models.CharField(blank=True, default='Poor', max_length=255, verbose_name='Core Functions - Improving Research Productivity Adjectival Rating'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='core_prod_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='core_tech_adjectival_rating',
            field=models.CharField(blank=True, default='Poor', max_length=255, verbose_name='Core Functions - Technical Advisory/Extension Adjectival RAting'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='final_adjectival_rating',
            field=models.CharField(blank=True, default='Poor', max_length=255, verbose_name='Final Adjectival Rating'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='final_numerical_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_adjectival_rating',
            field=models.CharField(blank=True, default='Poor', max_length=255, verbose_name='Strategic Functions Adjectival Rating'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='stra_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='supp_adjectival_rating',
            field=models.CharField(blank=True, default='Poor', max_length=255, verbose_name='Support Function Adjectival Rating'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='supp_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='tech_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
