# Generated by Django 3.1.7 on 2023-02-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0006_auto_20230212_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='function',
        ),
        migrations.RemoveField(
            model_name='item',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='personnel_ipcr',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='personnel_ipcr',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='personnel',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Personnel_IPCR',
        ),
        migrations.DeleteModel(
            name='Subitem',
        ),
    ]
