# Generated by Django 3.1.7 on 2023-02-14 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasundayag', '0007_auto_20230212_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.CharField(max_length=255)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfo_pap', models.TextField(blank=True, null=True)),
                ('indicators', models.TextField(blank=True, null=True)),
                ('accomplishments', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.area')),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'Functions',
            },
        ),
        migrations.CreateModel(
            name='Subfunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfo_pap', models.TextField(blank=True, null=True)),
                ('indicators', models.TextField(blank=True, null=True)),
                ('accomplishments', models.TextField(blank=True, null=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=50)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.function')),
            ],
            options={
                'verbose_name': 'Subfunction',
                'verbose_name_plural': 'Subfunctions',
            },
        ),
        migrations.CreateModel(
            name='PersonnelSubfunctionIPCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('period', models.CharField(choices=[('Jan-Jun', 'January to June'), ('Jul-Dec', 'July to December')], max_length=8)),
                ('rating_Q', models.FloatField(blank=True, default=0.0, null=True)),
                ('rating_E', models.FloatField(blank=True, default=0.0, null=True)),
                ('rating_T', models.FloatField(blank=True, default=0.0, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('personnel', models.ForeignKey(limit_choices_to=models.Q(models.Q(_negated=True, is_superuser=True), models.Q(_negated=True, is_staff=True)), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subfunction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.function')),
            ],
            options={
                'verbose_name': 'Personnel Subfunction Rating',
                'verbose_name_plural': 'Personnel Subfunction Ratings',
            },
        ),
        migrations.CreateModel(
            name='PersonnelFunctionIPCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('period', models.CharField(choices=[('Jan-Jun', 'January to June'), ('Jul-Dec', 'July to December')], max_length=8)),
                ('rating_Q', models.FloatField(blank=True, default=0.0, null=True)),
                ('rating_E', models.FloatField(blank=True, default=0.0, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.function')),
                ('personnel', models.ForeignKey(limit_choices_to=models.Q(models.Q(_negated=True, is_superuser=True), models.Q(_negated=True, is_staff=True)), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel Function Rating',
                'verbose_name_plural': 'Personnel Function Ratings',
            },
        ),
    ]
