# Generated by Django 4.1.6 on 2023-02-11 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0007_auto_20230207_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='ipcr_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.ipcrtype'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.rank'),
        ),
        migrations.AlterField(
            model_name='ipcrimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipcrspecification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipcrspecification',
            name='ipcr_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.ipcrtype'),
        ),
        migrations.AlterField(
            model_name='ipcrspecificationvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipcrspecificationvalue',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.ipcrspecification'),
        ),
        migrations.AlterField(
            model_name='ipcrtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
