# Generated by Django 3.1.7 on 2023-03-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0008_auto_20230318_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr',
            name='slug',
        ),
    ]
