# Generated by Django 3.1.7 on 2023-02-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0008_area_function_personnelfunctionipcr_personnelsubfunctionipcr_subfunction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='accomplishments',
        ),
        migrations.RemoveField(
            model_name='subfunction',
            name='accomplishments',
        ),
        migrations.AddField(
            model_name='personnelfunctionipcr',
            name='accomplishments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnelsubfunctionipcr',
            name='accomplishments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
