# Generated by Django 3.1.7 on 2023-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0009_remove_ipcr_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr',
            name='annual_adjectival_rating',
            field=models.CharField(blank=True, default='Poor', max_length=255, verbose_name='Final Adjectival Rating'),
        ),
        migrations.AddField(
            model_name='ipcr',
            name='annual_numerical_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
