# Generated by Django 3.1.7 on 2023-02-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0009_auto_20230214_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pasundayag.rank'),
        ),
    ]
