# Generated by Django 3.1.7 on 2023-03-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0010_auto_20230323_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcr',
            name='annual_adjectival_rating',
        ),
        migrations.RemoveField(
            model_name='ipcr',
            name='annual_numerical_rating',
        ),
    ]
