# Generated by Django 3.1.7 on 2023-02-14 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0010_area_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.rank'),
        ),
    ]
