# Generated by Django 3.1.7 on 2023-02-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0011_auto_20230214_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='decription',
            new_name='description',
        ),
    ]
