# Generated by Django 3.1.7 on 2023-03-24 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasundayag', '0011_auto_20230324_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnulaIPCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('jan_jun_final_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('jul_dec_final_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('annual_numerical_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('annual_adjectival_rating', models.CharField(blank=True, default='Poor', max_length=255, verbose_name='Final Adjectival Rating')),
                ('personnel', models.ForeignKey(limit_choices_to=models.Q(models.Q(_negated=True, is_superuser=True), models.Q(_negated=True, is_staff=True)), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
