# Generated by Django 3.1.7 on 2023-02-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0012_auto_20230214_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='function',
            name='mfo_pap',
            field=models.TextField(blank=True, null=True, verbose_name='MFO/PAP'),
        ),
        migrations.AlterField(
            model_name='subfunction',
            name='mfo_pap',
            field=models.TextField(blank=True, null=True, verbose_name='MFO/PAP'),
        ),
    ]
