# Generated by Django 3.1.7 on 2023-03-24 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasundayag', '0012_annulaipcr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnnulaIPCR',
            new_name='AnnualIPCR',
        ),
    ]
