# Generated by Django 3.1.7 on 2023-03-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0013_auto_20230324_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualipcr',
            options={'verbose_name': 'Annual IPCR', 'verbose_name_plural': 'Annual IPCRs'},
        ),
        migrations.AlterField(
            model_name='annualipcr',
            name='jan_jun_final_rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='jan_jun_rating', to='pasundayag.ipcr'),
        ),
        migrations.AlterField(
            model_name='annualipcr',
            name='jul_dec_final_rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='jul_dec_rating', to='pasundayag.ipcr'),
        ),
        migrations.AlterField(
            model_name='ipcr',
            name='final_numerical_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
