# Generated by Django 3.1.7 on 2023-02-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0014_auto_20230214_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-description'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['-mfo_pap'], 'verbose_name': 'Function', 'verbose_name_plural': 'Functions'},
        ),
        migrations.AlterModelOptions(
            name='subfunction',
            options={'ordering': ['-mfo_pap'], 'verbose_name': 'Subfunction', 'verbose_name_plural': 'Subfunctions'},
        ),
        migrations.AddField(
            model_name='personnelfunctionipcr',
            name='rating_T',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
