# Generated by Django 3.1.7 on 2023-03-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0014_auto_20230324_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnualIPCR',
        ),
    ]
