# Generated by Django 3.1.7 on 2023-03-24 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasundayag', '0015_delete_annualipcr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualIPCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('annual_numerical_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('annual_adjectival_rating', models.CharField(blank=True, default='Poor', max_length=255, verbose_name='Annual Adjectival Rating')),
                ('jan_jun_final_rating', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='jan_jun_rating', to='pasundayag.ipcr')),
                ('jul_dec_final_rating', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='jul_dec_rating', to='pasundayag.ipcr')),
                ('personnel', models.ForeignKey(limit_choices_to=models.Q(models.Q(_negated=True, is_superuser=True), models.Q(_negated=True, is_staff=True)), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annual IPCR',
                'verbose_name_plural': 'Annual IPCRs',
            },
        ),
    ]
