# Generated by Django 3.1.7 on 2023-02-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0015_auto_20230214_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelfunctionipcr',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='personnelsubfunctionipcr',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
