# Generated by Django 3.1.7 on 2023-02-14 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0016_auto_20230214_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelsubfunctionipcr',
            name='subfunction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pasundayag.subfunction'),
        ),
    ]
