# Generated by Django 3.1.7 on 2023-03-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0016_annualipcr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualipcr',
            name='jan_jun_final_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jan_jun_rating', to='pasundayag.ipcr'),
        ),
        migrations.AlterField(
            model_name='annualipcr',
            name='jul_dec_final_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jul_dec_rating', to='pasundayag.ipcr'),
        ),
    ]
