# Generated by Django 3.1.7 on 2023-02-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0017_auto_20230214_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['description'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['mfo_pap'], 'verbose_name': 'Function', 'verbose_name_plural': 'Functions'},
        ),
        migrations.AlterModelOptions(
            name='subfunction',
            options={'verbose_name': 'Subfunction', 'verbose_name_plural': 'Subfunctions'},
        ),
        migrations.AlterField(
            model_name='personnelfunctionipcr',
            name='period',
            field=models.CharField(choices=[('Jan-Jun', 'January to June'), ('Jul-Dec', 'July to December')], default='Select period', max_length=8),
        ),
        migrations.AlterField(
            model_name='personnelsubfunctionipcr',
            name='period',
            field=models.CharField(choices=[('Jan-Jun', 'January to June'), ('Jul-Dec', 'July to December')], default='Select Period', max_length=8),
        ),
    ]
