# Generated by Django 3.1.7 on 2023-03-31 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0017_auto_20230324_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcr',
            name='rank',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualipcr',
            name='jan_jun_final_rating',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(period='Jan-Jun'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jan_jun_rating', to='pasundayag.ipcr'),
        ),
        migrations.AlterField(
            model_name='annualipcr',
            name='jul_dec_final_rating',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(period='Jul-Dec'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jul_dec_rating', to='pasundayag.ipcr'),
        ),
    ]
