# Generated by Django 3.1.7 on 2023-03-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0018_auto_20230331_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr',
            name='rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
