# Generated by Django 3.1.7 on 2023-03-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0019_auto_20230331_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='parent',
        ),
    ]
