# Generated by Django 3.1.7 on 2023-03-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0020_remove_rank_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='level',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='tree_id',
        ),
    ]
