# Generated by Django 3.1.7 on 2023-03-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasundayag', '0022_auto_20230331_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualipcr',
            name='rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
