# Generated by Django 3.1.7 on 2023-02-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryoptions',
            options={'verbose_name': 'Evaluate', 'verbose_name_plural': 'Evaluate'},
        ),
    ]
